
version: 2.1

jobs:

  test:

    docker:

      - image: cimg/base:stable

    steps:

      - checkout

      - run:

          name: "This is build job"

          command: "echo This is build job"

  build:

    docker:

      - image: cimg/base:stable

    steps:

      - checkout

      - run:

          name: "This is test job"

          command: "echo This is test job"

  prod:

    docker:

      - image: cimg/base:stable

    steps:

      - checkout

      - run:

          name: "This is prod job"

          command: "echo This is prod job"

         

workflows:

  test_build_prod:

    jobs:

      - test

      - prod:

          requires:

              - test

      - build:

         requires:

           - prod