version: 2.1

jobs:
 
  test:

    docker:

      - image: cimg/base:stable

    steps:

      - checkout

      - run:

          name: "This is build job"

          command: "echo This is build job"

  build:

    docker:

      - image: cimg/base:stable

    steps:

      - checkout

      - run:

          name: "This is test job"

          command: "echo This is test job"

  prod:

    docker:

       - image: cimg/openjdk:16.0
    working_directory: ~/circleCiTesting
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - run: java --version
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline
      - run:
          name: Install latest version of ChromeDriver Sample
          command: |
            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update
            sudo apt-get install google-chrome-unstable
            sudo wget https://chromedriver.storage.googleapis.com/99.0.4844.51/chromedriver_linux64.zip
            sudo unzip chromedriver_linux64.zip
            sudo rm chromedriver_linux64.zip
            sudo mv chromedriver /usr/bin/
            sudo chmod 777 /usr/bin/chromedriver
            sudo apt-get install libxi6 libgconf-2-4
            sudo apt-get -y install xvfb gtk2-engines-pixbuf
            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable
            sudo apt-get install xvfb
            sudo apt-get -y install imagemagick x11-apps
      #- run: google-chrome --version
      - run:
          name: Running X virtual framebuffer
          command: Xvfb :0 -ac &

      - run:
          name: Run Tests
          command: |
            export DISPLAY=:99
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      # Then run your tests!
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path: target/surefire-reports
          destination: tr1
      - store_test_results:
          path: target/surefire-reports
         

workflows:

  test_build_prod:

    jobs:
        
      - test

      - prod:

          requires:

              - test

      - build:

         requires:

           - prod