version: 2.1



orbs:
  
  maven: circleci/maven@1.3.0
  win: circleci/windows@4.1.1

jobs:

 

   build-and-test:

    executor: win/server-2022

   

   

    steps:

      - run: 'Write-Host ''Hello, Windows'''

      - checkout

     

      - run:

          name: Build

          command: mvn -B -DskipTests clean package

     

      - run:

          name: Test

          command: mvn test




workflows:

  maven_test:
    jobs:
      - maven/test:
          command: '-X verify'